name: deploy-dev

on:
  push:
    branches: [master]

jobs:
  publish-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2

      - name: Make mission pbo
        uses: team-gsri/actions-make-pbo@master
        with:
          mission: CONT_Orion.Malden
          briefingName: "[GSRI] Orion dev-${{ github.sha }}"

      - name: Upload pbo to github
        uses: actions/upload-artifact@v2
        with:
          name: mission-pbo
          path: CONT_Orion.Malden.pbo

      - name: Publish mission to dev server
        uses: team-gsri/actions-deploy-mission@master
        env:
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_HOSTS_KEYS }}
          SSH_HOSTNAME: ${{ secrets.SSH_ARMA3_HOSTNAME }}
          SSH_USERNAME: ${{ secrets.SSH_ARMA3_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        with:
          localPath: CONT_Orion.Malden.pbo
          remotePath: ${{ secrets.ARMA3_PATH }}/mpmissions/CONT_Orion_dev.Malden.pbo
          instanceName: ${{ secrets.ARMA3_INSTANCE_DEV }}
